[iaaa]   # 北大门户的学号和密码
username = 2700114514
password = asdf1234

[epe]   # 智慧场馆系统需要的手机号
phone = 13800000000

###################################
#       Captcha Recognition       #
###################################

[recognize]   # 验证码识别平台，可选 ttshitu 或 chaojiying，下面只需填写该平台的账号信息
method = ttshitu

[recognize:ttshitu]   # TT 识图的用户名、密码
username = AceTaffy
password = gzyctfxxm

[recognize:chaojiying]   # 超级鹰的用户名、密码、软件 ID
username = 20260431ChihayaAnon
password = 521soyo0
softid = 998001

###################################
#     Notification (Optional)     #
###################################

[notify]   # 通知方式，可选 email、sc3、sct、bark，下面只需填写该方式所需的配置，也可填 none 表示不通知
method = none

[notify:email]   # 邮箱地址和登录授权码（不是原始密码）
email = 2700114514@stu.pku.edu.cn
password = Auth1919Code810

[notify:sc3]   # ServerChan3 的 SendKey
sendkey = sctp...

[notify:sct]   # ServerChanTurbo 的 SendKey
sendkey = SCT...

[notify:bark]   # Bark 的推送 Key
sendkey = LanDeBianLe
